# Copyright © 2013 Bart Massey
# This program is licensed under the GPL version 2 or later.
# Please see the file COPYING in this distribution for
# license terms.

gen-testcases: gen-testcases.hs
	ghc -Wall --make gen-testcases.hs

clean:
	-rm -f gen-testcases gen-testcases.hi gen-testcases.o
